### ISSUE TITLE
Comment view persists from previously viewed ticket

### ISSUE THREAD

**Issue by durka** [Code-Militia/jirust#149]
Thanks for sharing your project. I found a minor issue.

Steps to reproduce:
1. Enter comments view on a ticket (TKT-1) that has comments.
2. Leave and enter comments view on another ticket (TKT-2) that has comments.
3. BUG: The body of the comment shown is from TKT-1

**Comment by durka** [comment]
Assuming TKT-2 has multiple comments, pressing `j` and then `k` is enough to refresh and show the actual comment body for TKT-2.

**Comment by durka** [comment]
There is a similar bug in the main view. When `r` causes the ticket list to change, the Description pane does not update until I select another ticket and come back, so immediately after the refresh it shows the description of the wrong ticket.

**Comment by moali87** [comment]
Hi, thank you for reporting this bug.  I will look at it ASAP

**Comment by moali87** [comment]
I will make sure the contents are cleared when exiting out of the ticket comments view.  In the future the cache will be used to store the written contents of comments for each ticket.  This way you will be able to comment on a ticket, exit without pushing to JIRA, go to another ticket, write some comments there, come back to the original ticket with your original comments ready.

**Comment by moali87** [comment]
Fix for comment cache surviving multiple tickets https://github.com/Code-Militia/jirust/pull/143/commits/bb0e3164270900ab61838da6998059a5edab35bb

Fix for ticket description remaining post ticket refresh https://github.com/Code-Militia/jirust/pull/143/commits/c9fae8a7f8ae8b66ab2849e970e87ab8562fc510

**Comment by moali87** [comment]
@durka This should be fixed now with the latest 1.2.1 update.  Thank you for reporting the issues.
